### ISSUE TITLE
Production ready checklist

### ISSUE THREAD

**Issue by nshoes** [ipvideomarketinfo/face-detect#3]
- [ ] https://github.com/ipvideomarketinfo/ipvm.com/issues/4336
- [ ] job canceling bugs
- [ ] handle message queue better for job canceling and progress
- [ ] authentication with Rails app
- [ ] `ipvm.com` main navigation
- [ ] SSL for `ai.ipvm.com`
